// <auto-generated />
namespace MyAnime_DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class deleteOfWriterSeries : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(deleteOfWriterSeries));
        
        string IMigrationMetadata.Id
        {
            get { return "202012121536058_deleteOfWriterSeries"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
